[runtime]
log_level="WARNING"
dlthub_telemetry = true
workspace_id = "8ff9d79d-3f7e-4f86-849d-9e1c2abee4b8"
organization_id = "a82537a0-b666-46af-af6b-e80b55b957cb"

[destination.warehouse]
destination_type="duckdb"

[workspace.settings]
name = "playground"
